import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/rootcomps/sidebar/sidebar";
import Header from "@/components/rootcomps/header/header";
import { SidebarProvider } from "@/components/ui/sidebar";
import StoreProvider from "@/providers/ReduxProvider";


const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-[var(--global-bg)] overflow-hidden`}
      >
        <StoreProvider>
          <Header />
          <SidebarProvider>
            <Sidebar />

              
            <div className="relative overflow-y-auto h-dvh w-full py-3 px-5">
              {children}
            </div>
          </SidebarProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
